export PORT="${PORT-/dev/esp8266}"
export FQBN="${FQBN-esp8266:esp8266:nodemcuv2:baud=921600}"
export DEBUG="${DEBUG-}"
export SERIAL_INFO="${SERIAL_INFO-}"
export OLED_INFO="${OLED_INFO-1}"
export WIFI_SSID="${WIFI_SSID-}"
export WIFI_PASSWORD="${WIFI_PASSWORD-}"
export SKETCH="$(dirname "${BASH_SOURCE[0]}"/)/.."
